[package]
name = "default-instance"
version = "0.1.0"
authors = ["Joshy"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'support/std',
    'system/std',
    'runtime-primitives/std',
]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '7c751574d8c53108e78440bfa5dffb80ab644972'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '7c751574d8c53108e78440bfa5dffb80ab644972'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '7c751574d8c53108e78440bfa5dffb80ab644972'

# [dependencies.rstd]
# default-features = false
# git = 'https://github.com/paritytech/substrate.git'
# package = "sp-std"
# rev = '7c751574d8c53108e78440bfa5dffb80ab644972'

[dev-dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '7c751574d8c53108e78440bfa5dffb80ab644972'

[dev-dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
rev = '7c751574d8c53108e78440bfa5dffb80ab644972'
