[package]
name = 'super-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'super-runtime'
path = '../super-runtime'

[dependencies]
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", branch = 'master' }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = 'master' }
