[package]
name = "weight-fee-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
weights = { path = "../../modules/weights", default_features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
branch = 'td-warnings'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
branch = 'td-warnings'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
branch = 'td-warnings'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
branch = 'td-warnings'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
branch = 'td-warnings'

[dependencies.substrate-session]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-session'
branch = 'td-warnings'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
branch = 'td-warnings'

[dependencies.transaction-payment]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
branch = 'td-warnings'

[dependencies.babe]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-babe'
branch = 'td-warnings'

[dependencies.babe-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-consensus-babe'
branch = 'td-warnings'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-executive'
branch = 'td-warnings'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
branch = 'td-warnings'

[dependencies.grandpa]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
branch = 'td-warnings'

[dependencies.randomness-collective-flip]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
branch = 'td-warnings'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
branch = 'td-warnings'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
branch = 'td-warnings'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
branch = 'td-warnings'

[dependencies.sp-runtime]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
branch = 'td-warnings'

[dependencies.sp-api]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'td-warnings'

[dependencies.block-builder-api]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
branch = 'td-warnings'

[dependencies.sc-transaction-pool]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sc-transaction-pool'
branch = 'td-warnings'

[dependencies.inherents]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
branch = 'td-warnings'

[dependencies.offchain-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
branch = 'td-warnings'


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.3" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-api/std",
	"rstd/std",
	"runtime-io/std",
	"support/std",
	"balances/std",
	"babe/std",
	"babe-primitives/std",
	"executive/std",
	"indices/std",
	"grandpa/std",
	"primitives/std",
	"randomness-collective-flip/std",
	"sp-runtime/std",
	"system/std",
	"timestamp/std",
	"sudo/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"offchain-primitives/std",
	"substrate-session/std",
	"transaction-payment/std",
	"block-builder-api/std",
	"inherents/std",
	"weights/std",
	# "sc-transaction-pool/std", # Removed because sc-transaction-pool doesn't ahve an std feature https://github.com/paritytech/substrate/blob/master/client/transaction-pool/Cargo.toml
]
