[package]
name = "weight-fee-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
weights = { path = "../../modules/weights", default_features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.substrate-session]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-session'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.transaction-payment]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.babe]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-babe'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.babe-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-consensus-babe'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-executive'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.grandpa]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.randomness-collective-flip]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.sp-runtime]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.sp-api]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.block-builder-api]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.tx-pool-api]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sc-transaction-pool'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.inherents]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'

[dependencies.offchain-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
rev = '5f0b3dde3f0a097f380c62d0257cf3838a7d8281'


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.3" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-api/std",
	"rstd/std",
	"runtime-io/std",
	"support/std",
	"balances/std",
	"babe/std",
	"babe-primitives/std",
	"executive/std",
	"indices/std",
	"grandpa/std",
	"primitives/std",
	"randomness-collective-flip/std",
	"sp-runtime/std",
	"system/std",
	"timestamp/std",
	"sudo/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"offchain-primitives/std",
	"substrate-session/std",
	"transaction-payment/std",
	"block-builder-api/std",
	"inherents/std",
	"weights/std",
]
