version: 2
jobs:
  check-modules:
    docker:
      - image: parity/rust:nightly
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Check Adding Machine
          command: |
            cd kitchen/modules/adding-machine
            cargo check
      - run:
          name: Check Basic Token
          command: |
            cd kitchen/modules/basic-token
            cargo check
      - run:
          name: Check Check Membership
          command: |
            cd kitchen/modules/check-membership
            cargo check
      - run:
          name: Check Currency Imbalances
          command: |
            cd kitchen/modules/currency-imbalances
            cargo check
      - run:
          name: Check Double Map
          command: |
            cd kitchen/modules/double-map
            cargo check
      - run:
          name: Check Gen Random
          command: |
            cd kitchen/modules/gen-random
            cargo check
      - run:
          name: Check Generic Event
          command: |
            cd kitchen/modules/generic-event
            cargo check
      - run:
          name: Check Hello Substrate
          command: |
            cd kitchen/modules/hello-substrate
            cargo check
      - run:
          name: Check Linked Map
          command: |
            cd kitchen/modules/linked-map
            cargo check
      - run:
          name: Check Lockable Currency
          command: |
            cd kitchen/modules/lockable-currency
            cargo check
      - run:
          name: Check Module Constant Config
          command: |
            cd kitchen/modules/module-constant-config
            cargo check
      - run:
          name: Check Reservable Currency
          command: |
            cd kitchen/modules/reservable-currency
            cargo check
      - run:
          name: Check Schedule on Finalize
          command: |
            cd kitchen/modules/schedule-on-finalize
            cargo check
      - run:
          name: Check Simple Event
          command: |
            cd kitchen/modules/simple-event
            cargo check
      - run:
          name: Check Simple Map
          command: |
            cd kitchen/modules/simple-map
            cargo check
      # - persist_to_workspace:
      #     # relative to working_directory
      #     root: "./"
      #     paths:
      #       - "./"

  #TODO Port the build from travis CI to here
  #build-book:



workflows:
  version: 2
  check-modules:
    jobs:
      - check-modules
      #     filters: *filter-non-gh-pages
      # - deploy:
      #     filters: *filter-only-master
      #     requires:
      #       - test
