[package]
name = "pow-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
weights = { path = "../../pallets/weights", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
branch = 'seun-manual-seal-finalizer'

[dependencies.runtime-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
branch = 'seun-manual-seal-finalizer'

[dependencies.version]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
branch = 'seun-manual-seal-finalizer'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'seun-manual-seal-finalizer'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'seun-manual-seal-finalizer'

[dependencies.sp-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'seun-manual-seal-finalizer'

[dependencies.balances]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
branch = 'seun-manual-seal-finalizer'

[dependencies.generic-asset]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-generic-asset'
branch = 'seun-manual-seal-finalizer'

[dependencies.transaction-payment]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
branch = 'seun-manual-seal-finalizer'

# [dependencies.babe]
# default-features = false
# git = 'https://github.com/paritytech/substrate.git'
# package = 'pallet-babe'
# branch = 'seun-manual-seal-finalizer'
#
# [dependencies.sp-consensus-babe]
# default-features = false
# git = 'https://github.com/paritytech/substrate.git'
# branch = 'seun-manual-seal-finalizer'

[dependencies.executive]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-executive'
branch = 'seun-manual-seal-finalizer'

[dependencies.indices]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
branch = 'seun-manual-seal-finalizer'

[dependencies.randomness-collective-flip]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
branch = 'seun-manual-seal-finalizer'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'seun-manual-seal-finalizer'

[dependencies.timestamp]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
branch = 'seun-manual-seal-finalizer'

[dependencies.sudo]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
branch = 'seun-manual-seal-finalizer'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
branch = 'seun-manual-seal-finalizer'

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'seun-manual-seal-finalizer'

[dependencies.block-builder-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
branch = 'seun-manual-seal-finalizer'

[dependencies.sp-transaction-pool]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'seun-manual-seal-finalizer'

[dependencies.inherents]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
branch = 'seun-manual-seal-finalizer'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
branch = 'seun-manual-seal-finalizer'


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# "babe/std",
	"balances/std",
	"block-builder-api/std",
	"executive/std",
	"generic-asset/std",
	# "grandpa/std",
	"indices/std",
	"inherents/std",
	"offchain-primitives/std",
	"parity-scale-codec/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"runtime-io/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	# "sp-consensus-babe/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-session/std",
	"sudo/std",
	"frame-support/std",
	"frame-system/std",
	"timestamp/std",
	"transaction-payment/std",
	"version/std",
	"weights/std",
  "sp-transaction-pool/std",
]
