[package]
name = "check-membership"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'support/std',
    'system/std',
    'runtime-primitives/std',
]

[dependencies]
parity-scale-codec = { version = "1.1.0", features = ["derive"], default-features = false }
support = { package = "frame-support", branch = 'master', git = 'https://github.com/paritytech/substrate.git', default_features = false }
system = { package = 'frame-system', branch = 'master', git = 'https://github.com/paritytech/substrate.git', default_features = false}
runtime-primitives = { package = 'sp-runtime', branch = 'master', git = 'https://github.com/paritytech/substrate.git', default_features = false }
rstd = { package = 'sp-std', branch = 'master', git = 'https://github.com/paritytech/substrate.git', default_features = false }
primitives = { package = 'sp-core', branch = 'master', git = 'https://github.com/paritytech/substrate.git', default_features = false }
runtime-io = { package = 'sp-io', branch = 'master', git = 'https://github.com/paritytech/substrate.git', default_features = false }
