[package]
name = "ocw-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
# Substrate Pallets
balances = { package = 'pallet-balances', version = '2.0.0-alpha.5', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', version = '2.0.0-alpha.5', default-features = false }
# Recipe Pallets
offchain-demo = { path = "../../pallets/offchain-demo", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false

package = "sp-std"
version = '2.0.0-alpha.5'

[dependencies.runtime-io]
default-features = false

package = 'sp-io'
version = '2.0.0-alpha.5'

[dependencies.version]
default-features = false

package = 'sp-version'
version = '2.0.0-alpha.5'

[dependencies.support]
default-features = false

package = 'frame-support'
version = '2.0.0-alpha.5'

[dependencies.sp-core]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.substrate-session]
default-features = false

package = 'sp-session'
version = '2.0.0-alpha.5'

[dependencies.babe]
default-features = false

package = 'pallet-babe'
version = '2.0.0-alpha.5'

[dependencies.sp-consensus-babe]
default-features = false

version = '0.8.0-alpha.5'

[dependencies.sp-finality-grandpa]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.executive]
default-features = false

package = 'frame-executive'
version = '2.0.0-alpha.5'

[dependencies.indices]
default-features = false

package = 'pallet-indices'
version = '2.0.0-alpha.5'

[dependencies.grandpa]
default-features = false

package = 'pallet-grandpa'
version = '2.0.0-alpha.5'

[dependencies.randomness-collective-flip]
default-features = false

package = 'pallet-randomness-collective-flip'
version = '2.0.0-alpha.5'

[dependencies.system]
default-features = false

package = 'frame-system'
version = '2.0.0-alpha.5'

[dependencies.timestamp]
default-features = false

package = 'pallet-timestamp'
version = '2.0.0-alpha.5'

[dependencies.sudo]
default-features = false

package = 'pallet-sudo'
version = '2.0.0-alpha.5'

[dependencies.sp-runtime]
default-features = false

package = 'sp-runtime'
version = '2.0.0-alpha.5'

[dependencies.sp-api]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.block-builder-api]
default-features = false

package = 'sp-block-builder'
version = '2.0.0-alpha.5'

[dependencies.sp-transaction-pool]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.inherents]
default-features = false

package = 'sp-inherents'
version = '2.0.0-alpha.5'

[dependencies.offchain-primitives]
default-features = false

package = 'sp-offchain'
version = '2.0.0-alpha.5'

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# Substrate dependencies alphabetically
	"babe/std",
	"balances/std",
	"block-builder-api/std",
	"executive/std",
	"grandpa/std",
	"indices/std",
	"inherents/std",
	"offchain-primitives/std",
	"parity-scale-codec/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"runtime-io/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-runtime/std",
	"sp-transaction-pool/std",
	"substrate-session/std",
	"sudo/std",
	"support/std",
	"system/std",
	"timestamp/std",
	"transaction-payment/std",
	"version/std",

	# Recipes pallets
	"offchain-demo/std",
]
