[package]
name = "sum-storage-runtime-api"
version = "2.0.0"
authors = ["Joshy Orndorff"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
<<<<<<< HEAD
sp-api = { version = '2.0.0-rc2', default-features = false}
=======
sp-api = { version = '2.0.0-alpha.8', default-features = false}
>>>>>>> master

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
]
