[package]
name = "super-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
simple-event = { package = "simple-event", path = "../../modules/simple-event", default_features = false }
generic-event = { package = "generic-event", path = "../../modules/generic-event", default_features = false }
adding-machine = { package = "adding-machine", path = "../../modules/adding-machine", default-features = false }
single-value = { package = "single-value", path = "../../modules/single-value", default-features = false }
vec-set = { package = "vec-set", path = "../../modules/vec-set", default-features = false }
storage-cache = { package = "storage-cache", path = "../../modules/storage-cache", default-features = false }
simple-map = { package = "simple-map", path = "../../modules/simple-map", default-features = false }
double-map = { package = "double-map", path = "../../modules/double-map", default-features = false }
linked-map = { package = "linked-map", path = "../../modules/linked-map", default-features = false }
struct-storage = { package = "struct-storage", path = "../../modules/struct-storage", default-features = false }
module-constant-config = { package = "module-constant-config", path = "../../modules/module-constant-config", default-features = false }
basic-token = { package = "basic-token", path = "../../modules/basic-token", default-features = false }
check-membership = { package = "check-membership", path = "../../modules/check-membership", default-features = false }
execution-schedule = { package = "execution-schedule", path = "../../modules/execution-schedule", default-features = false }
smpl-treasury = { package = "smpl-treasury", path = "../../modules/smpl-treasury", default-features = false }
last-caller = { path = "../../modules/last-caller", default-features = false }
default-instance = { path = "../../modules/default-instance", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.1.0'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
branch = 'master'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
branch = 'master'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
branch = 'master'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
branch = 'master'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
branch = 'master'

[dependencies.substrate-session]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-session'
branch = 'master'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
branch = 'master'

[dependencies.transaction-payment]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
branch = 'master'

[dependencies.babe]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-babe'
branch = 'master'

[dependencies.babe-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-consensus-babe'
branch = 'master'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-executive'
branch = 'master'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
branch = 'master'

[dependencies.grandpa]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
branch = 'master'

[dependencies.randomness-collective-flip]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
branch = 'master'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
branch = 'master'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
branch = 'master'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
branch = 'master'

[dependencies.sp-runtime]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
branch = 'master'

[dependencies.sp-api]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'

[dependencies.block-builder-api]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
branch = 'master'

[dependencies.sc-transaction-pool]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sc-transaction-pool'
branch = 'master'

[dependencies.inherents]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
branch = 'master'

[dependencies.offchain-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
branch = 'master'


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.3" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-api/std",
	"rstd/std",
	"runtime-io/std",
	"support/std",
	"balances/std",
	"babe/std",
	"babe-primitives/std",
	"executive/std",
	"indices/std",
	"grandpa/std",
	"primitives/std",
	"randomness-collective-flip/std",
	"sp-runtime/std",
	"system/std",
	"timestamp/std",
	"sudo/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"offchain-primitives/std",
	"substrate-session/std",
	"simple-event/std",
	"generic-event/std",
	"adding-machine/std",
	"single-value/std",
	"vec-set/std",
	"storage-cache/std",
	"simple-map/std",
	"double-map/std",
	"linked-map/std",
	"struct-storage/std",
	"module-constant-config/std",
	"basic-token/std",
	"check-membership/std",
	"execution-schedule/std",
	"transaction-payment/std",
	"block-builder-api/std",
	"inherents/std",
]
