[package]
name = "account-set"
version = "2.0.0-dev"
authors = ["Joshy Orndorff"]
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A trait that supplies a set of accounts for use in a Substrate runtime"

[package.metadata.substrate]
categories = [
	"trait",
	"accounts",
	"recipe",
]
compatibility_version = "2.0.0-dev"

[features]
default = ['std']
std = [
    'sp-std/std',
]

[dependencies]
sp-std = { version = '2.0.0-dev', git = 'https://github.com/paritytech/substrate', rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d', default-features = false }
