[package]
name = "storage-cache"
version = "3.0.0"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A pallet that demonstrates caching values read from storage to improve performance"
license = "GPL-3.0-or-later"

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '2.0' }

# Substrate packages
frame-support = { package = 'frame-support', version = '3.0', default-features = false }
frame-system = { package = 'frame-system', version = '3.0', default-features = false }
sp-runtime = { version = '3.0', default-features = false }
sp-std = { version = '3.0', default-features = false }

[dev-dependencies]
sp-core = { version = '3.0', default-features = false }
sp-io = { version = '3.0', default-features = false }

[features]
default = ['std']
std = [
	'frame-support/std',
	'frame-system/std',
	'parity-scale-codec/std',
	'sp-runtime/std',
]
