name: Build and Deploy Book

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-deploy-book:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        # mdbook-version: '0.3.5'
        mdbook-version: 'latest'

    - name: Build Book
      run: mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: pr-publish
        publish_dir: ./book
