name: Check Links

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - test-ci # always want to including test-ci for testing gh-action

jobs:
  markdown-link-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
