name: Test Code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  test-code:
    name:                          Clippy, Check, Test
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    runs-on:                       ubuntu-latest
    container:
      image:                       paritytech/ci-linux:production
      volumes:
        - /home/runner/cache:/cache
    env:
      RUST_BACKTRACE:              full
      SCCACHE_IDLE_TIMEOUT:        0
      SCCACHE_DIR:                 /cache/${{ github.head_ref }}/${{ matrix.toolchain }}/sccache
      CMAKE_C_COMPILER_LAUNCHER:   sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache

    steps:
      - name:                      Cancel previous runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}

      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      
      - name:                      Configure CARGO_HOME & CARGO_TARGET_DIR
        run:                       ./.github/workflows/ci-cache.sh "${{ github.head_ref }}" "${{ matrix.toolchain }}"
      
      - name:                      Check cache
        if:                        github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'
        continue-on-error:         true
        shell:                     bash
        run:                       |
            echo "Copy cache from master";
            apt update&&apt install rsync -y;
            rsync -aq /cache/${{ matrix.toolchain }}/ $CARGO_TARGET_DIR/ || true;

      - name:                      Cache CARGO_HOME, CARGO_TARGET_DIR, SCCACHE_DIR
        uses:                      actions/cache@v2
        with:
          path:                    |
            /cache/${{ github.head_ref }}/${{ matrix.toolchain }}
          # /home/runner/cache/${{ github.head_ref }}/${{ matrix.toolchain }}
          # $CARGO_HOME
          key:                     ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          # key:                     ${{ runner.os }}-cargo-${{ github.head_ref }}
      
      - name:                      Cache stats
        shell:                     bash
        run:                       |
          sccache --show-stats
          echo "SCCACHE_DIR:"
          echo $SCCACHE_DIR
          ls $SCCACHE_DIR
          echo "CARGO_HOME:"
          echo $CARGO_HOME
          ls $CARGO_HOME
          echo "CARGO_TARGET_DIR:"
          echo $CARGO_TARGET_DIR
          ls $CARGO_TARGET_DIR
          echo "/cache/${{ github.head_ref }}/${{ matrix.toolchain }}:"
          ls /cache/${{ github.head_ref }}/${{ matrix.toolchain }}

## Test stage

      - name:                      Install nightly clippy
        if:                        matrix.toolchain == 'nightly'
        shell:                     bash
        run:                       rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu

      - name:                      Run nightly clippy
        if:                        matrix.toolchain == 'nightly'
        uses:                      actions-rs/cargo@master
        with:
          command:                 clippy
          toolchain:               nightly
          args:                    -- -D warnings
      
      - name:                      Checking Kitchen stable
        if:                        matrix.toolchain == 'stable'
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          args:                    --all  --verbose

      - name:                      Test Kitchen stable
        if:                        matrix.toolchain == 'stable'
        uses:                      actions-rs/cargo@master
        with:
          command:                 test
          args:                     --all --verbose
