name: Test Code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  test-code:
    name:                          Clippy, Check, Test
    strategy:
          matrix:
            toolchain:
              - stable
              - nightly
    runs-on:                       ubuntu-latest
    container:
      image:                       paritytech/ci-linux:production
      volumes:
        - /cache:/cache
    env:
      RUST_BACKTRACE:              full
      SCCACHE_DIR:                 /cache/$HEAD_REF/$TOOLCHAIN/sccache
      SCCACHE_IDLE_TIMEOUT:        0
      CMAKE_C_COMPILER_LAUNCHER:   sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache

    steps:
      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}

      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      
      - name:                      Configure CARGO_HOME & CARGO_TARGET_DIR
        run:                       ./.github/workflows/ci-cache.sh "${{ github.head_ref }}" "${{ matrix.toolchain }}"
      
      - name:                      Cache checking
        if:                        github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'
        continue-on-error:         true
        shell:                     bash
        run:                       |
            echo "Copy cache from master";
            apt update&&apt install rsync -y;
            rsync -aq /cache/${{ matrix.toolchain }}/ $CARGO_TARGET_DIR/ || true;
      
      - name:                      Sccache stats
        shell:                     bash
        run:                       sccache --show-stats

      - name:                      Install ${{ matrix.toolchain }} clippy
        shell:                     bash
        run:                       |
          rustup component add clippy --toolchain ${{ matrix.toolchain }}-x86_64-unknown-linux-gnu

      - name:                      Run ${{ matrix.toolchain }} clippy
        uses:                      actions-rs/cargo@master
        with:
          command:                 clippy
          toolchain:               ${{ matrix.toolchain }}
          args:                    -- -D warnings
      
      - name:                      Checking Kitchen ${{ matrix.toolchain }}
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          toolchain:               ${{ matrix.toolchain }}
          args:                    --all  --verbose

      - name:                      Test Kitchen ${{ matrix.toolchain }}
        uses:                      actions-rs/cargo@master
        with:
          command:                 test
          toolchain:               ${{ matrix.toolchain }}
          run:                     --all --verbose
